# -*- coding: utf-8 -*-
import json

NB_OUT = r"C:\Users\braid\OneDrive\Desktop\Data Driven Modeling Project\symbolic.ipynb"
cells = []

def md(src):
    lines = src.strip().split("\n")
    source = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "markdown", "metadata": {}, "source": source})

def code(src):
    lines = src.strip().split("\n")
    source = [l + "\n" for l in lines[:-1]] + [lines[-1]]
    cells.append({"cell_type": "code", "metadata": {}, "source": source, "outputs": [], "execution_count": None})

# ── Cell 1: Title ──
md(
"# PySR Symbolic Regression -- Hyperparameter Sweep & SINDy Comparison\n"
"\n"
"**2 Algorithms**: Standard PySR, Hybrid PySR (pooled runs)\n"
"\n"
"**Sweep axes**: parsimony x maxsize x library (No-lam / With-lam)\n"
"\n"
"**3 Metrics**: MSE, ATE (A/B/C/D/F), R-squared\n"
"\n"
"**3 Regimes**: Bouncing, Rolling, Flight | **3 DOFs**: a_x, a_y, a_theta\n"
"\n"
"| Sweep param | Values | Purpose |\n"
"|---|---|---|\n"
"| parsimony | 0.01, 0.1 | Complexity penalty (like SINDy threshold) |\n"
"| maxsize | 15, 25 | Expression cap (like SINDy library size) |\n"
"| library | No-lam, With-lam | Feature set (+/- contact forces) |\n"
"\n"
"**Total fits**: 2 x 2 x 2 x 2 x 3 x 3 = 144 (~10 min)\n"
"\n"
"ATE grading: A < 0.01, B < 0.05, C < 0.15, D < 0.50, F >= 0.50"
)

# ── Cell 2: Imports ──
code(
"import sys, os, warnings, time\n"
"import numpy as np\n"
"import matplotlib.pyplot as plt\n"
"import pandas as pd\n"
"from sklearn.metrics import mean_squared_error\n"
"from IPython.display import display, HTML\n"
"warnings.filterwarnings('ignore')\n"
"\n"
"PROJ = r'C:\\Users\\braid\\OneDrive\\Desktop\\Data Driven Modeling Project'\n"
"sys.path.insert(0, PROJ)\n"
"\n"
"from pipeline.data_loader import load_all\n"
"from pipeline.preprocessing import regime_aware_split, temporal_split_frac\n"
"from pysr import PySRRegressor\n"
"\n"
"def compute_r2(y_true, y_pred):\n"
"    ss_res = np.sum((y_true - y_pred) ** 2)\n"
"    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)\n"
"    return 1.0 - ss_res / ss_tot if ss_tot > 1e-20 else 0.0\n"
"\n"
"def compute_open_loop_ate(y_pred_seg, q_true_seg, u_true_seg, dt):\n"
"    n = len(y_pred_seg)\n"
"    if n < 2:\n"
"        return 0.0\n"
"    q_sim = np.zeros(n)\n"
"    u_sim = np.zeros(n)\n"
"    q_sim[0] = q_true_seg[0]\n"
"    u_sim[0] = u_true_seg[0]\n"
"    for i in range(n - 1):\n"
"        u_sim[i + 1] = u_sim[i] + y_pred_seg[i] * dt\n"
"        q_sim[i + 1] = q_sim[i] + u_sim[i + 1] * dt\n"
"    return float(np.sqrt(np.mean((q_true_seg - q_sim) ** 2)))\n"
"\n"
"def ate_grade(ate):\n"
"    if not np.isfinite(ate): return 'F'\n"
"    if ate < 0.01: return 'A'\n"
"    if ate < 0.05: return 'B'\n"
"    if ate < 0.15: return 'C'\n"
"    if ate < 0.50: return 'D'\n"
"    return 'F'\n"
"\n"
"def safe_predict(model, X):\n"
"    y = model.predict(X)\n"
"    mask = ~np.isfinite(y)\n"
"    if mask.any():\n"
"        y[mask] = np.nanmean(y[~mask]) if (~mask).any() else 0.0\n"
"    return y\n"
"\n"
"DOF_LABELS = ['a_x', 'a_y', 'a_theta']\n"
"REGIMES = ['bouncing', 'rolling', 'flight']\n"
"\n"
"print('Imports loaded.')"
)

# ── Cell 3 ──
md("## S1 Data Loading & Splits")

# ── Cell 4: Data loading ──
code(
"all_runs = load_all()\n"
"\n"
"for regime, runs in all_runs.items():\n"
"    print(f'{regime.upper()} ({len(runs)} runs):')\n"
"    for r in runs:\n"
"        print(f'  {r.name}: N={r.N}, dt={r.dt:.6f}')\n"
"\n"
"# Standard PySR: first run, regime-aware 60/20/20\n"
"regime_data = {}\n"
"print('\\n--- Standard splits (first run, regime-aware 60/20/20) ---')\n"
"for regime in REGIMES:\n"
"    run = all_runs[regime][0]\n"
"    sp = regime_aware_split(run.N, run.lambda_N)\n"
"    regime_data[regime] = {'run': run, 'split': sp}\n"
"    print(f'  {regime}: train={len(sp.idx_train)} val={len(sp.idx_val)} test={len(sp.idx_test)}')\n"
"\n"
"# Hybrid PySR: pool all runs, temporal 60/20/20\n"
"pooled_data = {}\n"
"print('\\n--- Hybrid splits (pooled runs, temporal 60/20/20) ---')\n"
"for regime in REGIMES:\n"
"    runs = all_runs[regime]\n"
"    q_all = np.vstack([r.q for r in runs])\n"
"    u_all = np.vstack([r.u for r in runs])\n"
"    qddot_all = np.vstack([r.qddot for r in runs])\n"
"    lN_all = np.concatenate([r.lambda_N for r in runs])\n"
"    lF_all = np.concatenate([r.lambda_F for r in runs])\n"
"    dt = runs[0].dt\n"
"    N_pool = len(lN_all)\n"
"    sp = temporal_split_frac(N_pool, 0.60, 0.20)\n"
"    pooled_data[regime] = {\n"
"        'q': q_all, 'u': u_all, 'qddot': qddot_all,\n"
"        'lambda_N': lN_all, 'lambda_F': lF_all,\n"
"        'dt': dt, 'split': sp, 'N': N_pool,\n"
"    }\n"
"    print(f'  {regime}: N={N_pool} train={len(sp.idx_train)} val={len(sp.idx_val)} test={len(sp.idx_test)}')\n"
"\n"
"print('\\nData ready.')"
)

# ── Cell 5 ──
md(
"## S2 Sweep Configuration\n"
"\n"
"| Axis | Values | Count |\n"
"|---|---|---|\n"
"| parsimony | 0.01, 0.1 | 2 |\n"
"| maxsize | 15, 25 | 2 |\n"
"| library | No-lam (8 feat), With-lam (10 feat) | 2 |\n"
"| algorithm | PySR (single run), Hybrid PySR (pooled) | 2 |\n"
"| regime | bouncing, rolling, flight | 3 |\n"
"| DOF | a_x, a_y, a_theta | 3 |\n"
"\n"
"Fixed: niterations=20, populations=15, population_size=30"
)

# ── Cell 6: Config ──
code(
"ACCEL_NAMES = ['xddot', 'yddot', 'thetaddot']\n"
"\n"
"def _feat_names(target_dof, with_lambda=False):\n"
"    base = ['x', 'y', 'theta', 'xdot', 'ydot', 'thetadot']\n"
"    other = [ACCEL_NAMES[j] for j in range(3) if j != target_dof]\n"
"    names = base + other\n"
"    if with_lambda:\n"
"        names += ['lambda_N', 'lambda_F']\n"
"    return names\n"
"\n"
"def build_features(q, u, qddot, target_dof,\n"
"                   lambda_N=None, lambda_F=None, with_lambda=False):\n"
"    other_idx = [j for j in range(3) if j != target_dof]\n"
"    X = np.hstack([q, u, qddot[:, other_idx]])\n"
"    if with_lambda:\n"
"        X = np.hstack([X, lambda_N.reshape(-1, 1), lambda_F.reshape(-1, 1)])\n"
"    return X\n"
"\n"
"PARSIMONY_VALUES = [0.01, 0.1]\n"
"MAXSIZE_VALUES   = [15, 25]\n"
"LIB_VARIANTS     = [('No-lam', False), ('With-lam', True)]\n"
"ALGO_VARIANTS    = [('PySR', regime_data), ('Hybrid PySR', pooled_data)]\n"
"NITER = 20\n"
"POP_SIZE = 30\n"
"\n"
"n_fits = (len(PARSIMONY_VALUES) * len(MAXSIZE_VALUES) * len(LIB_VARIANTS)\n"
"          * len(ALGO_VARIANTS) * len(REGIMES) * len(DOF_LABELS))\n"
"print(f'Sweep: {len(PARSIMONY_VALUES)} parsimony x {len(MAXSIZE_VALUES)} maxsize'\n"
"      f' x {len(LIB_VARIANTS)} lib x {len(ALGO_VARIANTS)} algo'\n"
"      f' x {len(REGIMES)} regime x {len(DOF_LABELS)} DOF = {n_fits} fits')\n"
"print(f'Fixed: niterations={NITER}, population_size={POP_SIZE}')\n"
"print(f'Estimated time: ~{n_fits * 4 / 60:.0f} min')"
)

# ── Cell 7 ──
md(
"## S3 Full PySR Sweep\n"
"\n"
"Unified loop over all hyperparameter combinations."
)

# ── Cell 8: Sweep ──
code(
"all_rows = []\n"
"all_models = {}\n"
"t0_global = time.time()\n"
"fit_i = 0\n"
"\n"
"for pars in PARSIMONY_VALUES:\n"
"    for mxsz in MAXSIZE_VALUES:\n"
"        for lib_label, with_lam in LIB_VARIANTS:\n"
"\n"
"            for algo_name, data_source in ALGO_VARIANTS:\n"
"                for regime in REGIMES:\n"
"                    # get data + split\n"
"                    if algo_name == 'PySR':\n"
"                        run = data_source[regime]['run']\n"
"                        sp  = data_source[regime]['split']\n"
"                        q, u = run.q, run.u\n"
"                        lN, lF = run.lambda_N, run.lambda_F\n"
"                        qddot = run.qddot\n"
"                        dt = run.dt\n"
"                    else:\n"
"                        pdata = data_source[regime]\n"
"                        sp = pdata['split']\n"
"                        q, u = pdata['q'], pdata['u']\n"
"                        lN, lF = pdata['lambda_N'], pdata['lambda_F']\n"
"                        qddot = pdata['qddot']\n"
"                        dt = pdata['dt']\n"
"\n"
"                    for d, dof in enumerate(DOF_LABELS):\n"
"                        feat_names = _feat_names(d, with_lam)\n"
"                        X = build_features(q, u, qddot, d, lN, lF, with_lam)\n"
"                        X_tr  = X[sp.idx_train]\n"
"                        X_val = X[sp.idx_val]\n"
"                        X_te  = X[sp.idx_test]\n"
"                        fit_i += 1\n"
"                        y = qddot[:, d]\n"
"                        y_tr  = y[sp.idx_train]\n"
"                        y_val = y[sp.idx_val]\n"
"                        y_te  = y[sp.idx_test]\n"
"\n"
"                        tag = f'p={pars} ms={mxsz}'\n"
"                        print(f'[{fit_i}/{n_fits}] {algo_name:11s} | {regime:8s} | {lib_label:8s} | {tag} | {dof}',\n"
"                              end=' ', flush=True)\n"
"                        t1 = time.time()\n"
"\n"
"                        model = PySRRegressor(\n"
"                            niterations=NITER,\n"
"                            populations=15,\n"
"                            population_size=POP_SIZE,\n"
"                            binary_operators=['+', '-', '*', '/'],\n"
"                            unary_operators=['sin', 'cos', 'square'],\n"
"                            maxsize=mxsz,\n"
"                            parsimony=pars,\n"
"                            batching=True,\n"
"                            batch_size=256,\n"
"                            verbosity=0,\n"
"                        )\n"
"                        model.fit(X_tr, y_tr, variable_names=feat_names)\n"
"\n"
"                        yp_tr  = safe_predict(model, X_tr)\n"
"                        yp_val = safe_predict(model, X_val)\n"
"                        yp_te  = safe_predict(model, X_te)\n"
"                        yp_all = safe_predict(model, X)\n"
"\n"
"                        mse_tr  = float(mean_squared_error(y_tr, yp_tr))\n"
"                        mse_val = float(mean_squared_error(y_val, yp_val))\n"
"                        mse_te  = float(mean_squared_error(y_te, yp_te))\n"
"                        r2_val  = compute_r2(y_val, yp_val)\n"
"                        r2_te   = compute_r2(y_te, yp_te)\n"
"                        ate_v   = compute_open_loop_ate(\n"
"                            yp_all[sp.idx_val], q[sp.idx_val, d],\n"
"                            u[sp.idx_val, d], dt)\n"
"\n"
"                        eq_str = str(model.sympy())\n"
"                        try:\n"
"                            cplx = int(model.get_best()['complexity'])\n"
"                        except Exception:\n"
"                            cplx = -1\n"
"\n"
"                        key = (algo_name, regime, lib_label, pars, mxsz, dof)\n"
"                        all_models[key] = model\n"
"\n"
"                        all_rows.append({\n"
"                            'algorithm': algo_name, 'regime': regime,\n"
"                            'library': lib_label, 'parsimony': pars,\n"
"                            'maxsize': mxsz, 'dof': dof,\n"
"                            'n_terms': cplx,\n"
"                            'MSE_train': mse_tr, 'MSE_val': mse_val,\n"
"                            'MSE_test': mse_te,\n"
"                            'R2_val': r2_val, 'R2_test': r2_te,\n"
"                            'ATE': ate_v, 'ate_grade': ate_grade(ate_v),\n"
"                            'equation': eq_str,\n"
"                        })\n"
"                        elapsed = time.time() - t1\n"
"                        print(f'R2={r2_val:.3f} ATE={ate_v:.4f}({ate_grade(ate_v)}) {elapsed:.0f}s')\n"
"\n"
"df_pysr = pd.DataFrame(all_rows)\n"
"total_min = (time.time() - t0_global) / 60\n"
"print(f'\\nSweep complete: {len(df_pysr)} rows in {total_min:.1f} min')\n"
"print(f'Grade dist:\\n{df_pysr[\"ate_grade\"].value_counts().sort_index().to_string()}')"
)

# ── Cell 9 ──
md("## S4 Save Results")

# ── Cell 10: Save ──
code(
"csv_path = os.path.join(PROJ, 'pysr_sweep_results.csv')\n"
"df_pysr.to_csv(csv_path, index=False)\n"
"print(f'Saved {len(df_pysr)} rows to {csv_path}')\n"
"\n"
"print('\\n=== Mean metrics by algorithm ===')\n"
"print(df_pysr.groupby('algorithm')[['MSE_val','R2_val','ATE']].mean().to_string())\n"
"\n"
"print('\\n=== Mean metrics by parsimony ===')\n"
"print(df_pysr.groupby('parsimony')[['MSE_val','R2_val','ATE']].mean().to_string())\n"
"\n"
"print('\\n=== Mean metrics by maxsize ===')\n"
"print(df_pysr.groupby('maxsize')[['MSE_val','R2_val','ATE']].mean().to_string())\n"
"\n"
"print('\\n=== ATE grade distribution ===')\n"
"grade_ct = pd.crosstab(df_pysr['algorithm'], df_pysr['ate_grade'])\n"
"for g in ['A','B','C','D','F']:\n"
"    if g not in grade_ct.columns: grade_ct[g] = 0\n"
"print(grade_ct[['A','B','C','D','F']].to_string())"
)

# ── Cell 11 ──
md(
"## S5 Hyperparameter Analysis\n"
"\n"
"Which parsimony x maxsize combination works best?"
)

# ── Cell 12: Hyperparam heatmap ──
code(
"fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n"
"fig.suptitle('Mean ATE by Parsimony x Maxsize', fontsize=14, fontweight='bold')\n"
"\n"
"for col, regime in enumerate(REGIMES):\n"
"    for row, algo in enumerate(['PySR', 'Hybrid PySR']):\n"
"        ax = axes[row, col]\n"
"        sub = df_pysr[(df_pysr['algorithm'] == algo) & (df_pysr['regime'] == regime)]\n"
"        piv = sub.pivot_table(index='parsimony', columns='maxsize',\n"
"                              values='ATE', aggfunc='mean')\n"
"        im = ax.imshow(piv.values, cmap='RdYlGn_r', aspect='auto')\n"
"        ax.set_xticks(range(len(piv.columns)))\n"
"        ax.set_xticklabels(piv.columns)\n"
"        ax.set_yticks(range(len(piv.index)))\n"
"        ax.set_yticklabels([f'{v}' for v in piv.index])\n"
"        ax.set_xlabel('maxsize')\n"
"        ax.set_ylabel('parsimony')\n"
"        ax.set_title(f'{algo} - {regime.upper()}', fontweight='bold')\n"
"        for i in range(piv.shape[0]):\n"
"            for j in range(piv.shape[1]):\n"
"                v = piv.values[i, j]\n"
"                if np.isfinite(v):\n"
"                    ax.text(j, i, f'{v:.3f}', ha='center', va='center',\n"
"                            fontsize=11, fontweight='bold')\n"
"        plt.colorbar(im, ax=ax, shrink=0.8)\n"
"\n"
"plt.tight_layout(rect=[0, 0, 1, 0.95])\n"
"plt.savefig(os.path.join(PROJ, 'pysr_hyperparam_heatmap.png'), dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"print('Hyperparameter heatmap saved.')"
)

# ── Cell 13 ──
md(
"## S6 Internal Comparison -- PySR vs Hybrid PySR\n"
"\n"
"Best config per (algorithm x library x regime x DOF), compared on MSE / R2 / ATE."
)

# ── Cell 14: Internal comparison ──
code(
"fig, axes = plt.subplots(3, 3, figsize=(20, 14))\n"
"fig.suptitle('PySR vs Hybrid PySR (best configs) -- MSE / R2 / ATE', fontsize=15, fontweight='bold')\n"
"\n"
"# pick best config per (algo, lib, regime, dof) by ATE\n"
"idx_best = df_pysr.groupby(['algorithm','library','regime','dof'])['ATE'].idxmin()\n"
"df_best = df_pysr.loc[idx_best].copy()\n"
"\n"
"metrics = [('MSE_val', 'MSE (val)'), ('R2_val', 'R2 (val)'), ('ATE', 'ATE')]\n"
"for col, (metric, ylabel) in enumerate(metrics):\n"
"    for row, regime in enumerate(REGIMES):\n"
"        ax = axes[row, col]\n"
"        sub = df_best[df_best['regime'] == regime]\n"
"        groups = sub.groupby(['algorithm','library'])[metric].mean().reset_index()\n"
"        labels = [f'{a}\\n{l}' for a, l in zip(groups['algorithm'], groups['library'])]\n"
"        cmap = {'PySR/No-lam':'#4C72B0', 'PySR/With-lam':'#55A868',\n"
"                'Hybrid PySR/No-lam':'#C44E52', 'Hybrid PySR/With-lam':'#8172B2'}\n"
"        colors = [cmap.get(f'{a}/{l}', 'grey') for a, l in zip(groups['algorithm'], groups['library'])]\n"
"        bars = ax.bar(range(len(groups)), groups[metric], color=colors,\n"
"                      alpha=0.85, edgecolor='black', linewidth=0.5)\n"
"        ax.set_xticks(range(len(groups)))\n"
"        ax.set_xticklabels(labels, fontsize=8)\n"
"        ax.set_ylabel(ylabel, fontweight='bold')\n"
"        if row == 0: ax.set_title(ylabel, fontsize=12, fontweight='bold')\n"
"        ax.text(0.02, 0.95, regime.upper(), transform=ax.transAxes, fontsize=11,\n"
"                fontweight='bold', va='top',\n"
"                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))\n"
"        ax.grid(axis='y', alpha=0.3)\n"
"        for bar, val in zip(bars, groups[metric]):\n"
"            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height(),\n"
"                    f'{val:.4f}', ha='center', va='bottom', fontsize=7)\n"
"\n"
"plt.tight_layout(rect=[0, 0, 1, 0.96])\n"
"plt.savefig(os.path.join(PROJ, 'pysr_internal_comparison.png'), dpi=150, bbox_inches='tight')\n"
"plt.show()"
)

# ── Cell 15 ──
md("## S7 Best Equations")

# ── Cell 16: Equations ──
code(
"print('=' * 90)\n"
"print('BEST EQUATIONS (by ATE per algorithm x regime x DOF)')\n"
"print('=' * 90)\n"
"\n"
"for algo in ['PySR', 'Hybrid PySR']:\n"
"    print(f'\\n--- {algo} ---')\n"
"    sub = df_pysr[df_pysr['algorithm'] == algo]\n"
"    for regime in REGIMES:\n"
"        print(f'\\n  {regime.upper()}:')\n"
"        for dof in DOF_LABELS:\n"
"            rows = sub[(sub['regime'] == regime) & (sub['dof'] == dof)]\n"
"            if len(rows) == 0: continue\n"
"            best = rows.loc[rows['ATE'].idxmin()]\n"
"            eq = best['equation']\n"
"            if len(eq) > 95: eq = eq[:92] + '...'\n"
"            print(f'    {dof} [{best[\"library\"]} p={best[\"parsimony\"]} ms={best[\"maxsize\"]}]'\n"
"                  f' ATE={best[\"ATE\"]:.4f}({best[\"ate_grade\"]}) R2={best[\"R2_val\"]:.3f}')\n"
"            print(f'      {eq}')"
)

# ── Cell 17 ──
md(
"## S8 Cross-Method Comparison -- PySR vs SINDy Pipeline\n"
"\n"
"Load SINDy sweep results (3600 rows) and compare best configs head-to-head."
)

# ── Cell 18: Cross comparison ──
code(
"sindy_csv = os.path.join(PROJ, 'pipeline', 'full_sweep_results.csv')\n"
"df_sindy = pd.read_csv(sindy_csv)\n"
"print(f'SINDy results: {len(df_sindy)} rows, algorithms: {list(df_sindy[\"algorithm\"].unique())}')\n"
"\n"
"# best SINDy config per (algo, regime, dof)\n"
"sindy_best = []\n"
"for algo in df_sindy['algorithm'].unique():\n"
"    sub = df_sindy[df_sindy['algorithm'] == algo]\n"
"    for regime in REGIMES:\n"
"        for dof in DOF_LABELS:\n"
"            rows = sub[(sub['regime']==regime) & (sub['dof']==dof)].dropna(subset=['ATE'])\n"
"            if len(rows) == 0: continue\n"
"            b = rows.loc[rows['ATE'].idxmin()]\n"
"            sindy_best.append({\n"
"                'algorithm': b['algorithm'], 'regime': regime, 'dof': dof,\n"
"                'library': b['library'],\n"
"                'MSE_val': b['MSE_val'], 'MSE_test': b['MSE_test'],\n"
"                'R2_val': b.get('R2_val', np.nan), 'R2_test': b['R2_test'],\n"
"                'ATE': b['ATE'], 'ate_grade': b['ate_grade'],\n"
"            })\n"
"\n"
"# best PySR config per (algo, regime, dof)\n"
"pysr_best = []\n"
"for algo in ['PySR', 'Hybrid PySR']:\n"
"    sub = df_pysr[df_pysr['algorithm'] == algo]\n"
"    for regime in REGIMES:\n"
"        for dof in DOF_LABELS:\n"
"            rows = sub[(sub['regime']==regime) & (sub['dof']==dof)].dropna(subset=['ATE'])\n"
"            if len(rows) == 0: continue\n"
"            b = rows.loc[rows['ATE'].idxmin()]\n"
"            pysr_best.append({\n"
"                'algorithm': b['algorithm'], 'regime': regime, 'dof': dof,\n"
"                'library': b['library'],\n"
"                'MSE_val': b['MSE_val'], 'MSE_test': b['MSE_test'],\n"
"                'R2_val': b['R2_val'], 'R2_test': b['R2_test'],\n"
"                'ATE': b['ATE'], 'ate_grade': b['ate_grade'],\n"
"            })\n"
"\n"
"df_cross = pd.concat([pd.DataFrame(sindy_best), pd.DataFrame(pysr_best)], ignore_index=True)\n"
"print(f'\\nCross-comparison: {len(df_cross)} best configs')\n"
"print(df_cross.groupby('algorithm')[['MSE_val','R2_val','ATE']].mean().to_string())"
)

# ── Cell 19 ──
md("## S8b Cross-Method Plots")

# ── Cell 20: Cross plots ──
code(
"all_algos = sorted(df_cross['algorithm'].unique())\n"
"cmap = plt.cm.Set2\n"
"acolors = {a: cmap(i / max(len(all_algos)-1, 1)) for i, a in enumerate(all_algos)}\n"
"\n"
"for metric, ylabel, title_word in [\n"
"    ('ATE', 'ATE (lower=better)', 'ATE'),\n"
"    ('R2_val', 'R2 (higher=better)', 'R2'),\n"
"    ('MSE_val', 'MSE (lower=better)', 'MSE'),\n"
"]:\n"
"    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
"    fig.suptitle(f'Best {title_word} by Regime -- All Algorithms', fontsize=14, fontweight='bold')\n"
"    for i, regime in enumerate(REGIMES):\n"
"        ax = axes[i]\n"
"        sub = df_cross[df_cross['regime'] == regime]\n"
"        vals = sub.groupby('algorithm')[metric].mean().reindex(all_algos)\n"
"        bars = ax.bar(range(len(all_algos)), vals.values,\n"
"                      color=[acolors[a] for a in all_algos],\n"
"                      edgecolor='black', linewidth=0.5, alpha=0.85)\n"
"        ax.set_xticks(range(len(all_algos)))\n"
"        ax.set_xticklabels(all_algos, fontsize=8, rotation=30, ha='right')\n"
"        ax.set_ylabel(ylabel, fontweight='bold')\n"
"        ax.set_title(regime.upper(), fontweight='bold')\n"
"        ax.grid(axis='y', alpha=0.3)\n"
"        fmt = '.6f' if 'MSE' in metric else '.4f'\n"
"        for bar, val in zip(bars, vals.values):\n"
"            if np.isfinite(val):\n"
"                ax.text(bar.get_x()+bar.get_width()/2, bar.get_height(),\n"
"                        f'{val:{fmt}}', ha='center', va='bottom', fontsize=7)\n"
"    plt.tight_layout(rect=[0, 0, 1, 0.93])\n"
"    plt.savefig(os.path.join(PROJ, f'cross_method_{title_word.lower()}.png'),\n"
"               dpi=150, bbox_inches='tight')\n"
"    plt.show()\n"
"print('Cross-method plots saved.')"
)

# ── Cell 21 ──
md("## S9 ATE Grade Heatmap -- All Methods")

# ── Cell 22: Heatmap ──
code(
"grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}\n"
"grade_labels = {4: 'A', 3: 'B', 2: 'C', 1: 'D', 0: 'F'}\n"
"\n"
"df_cross['grade_num'] = df_cross['ate_grade'].map(grade_map)\n"
"df_cross['label'] = df_cross['regime'] + ' / ' + df_cross['dof']\n"
"pivot = df_cross.pivot_table(index='algorithm', columns='label',\n"
"                             values='grade_num', aggfunc='max')\n"
"\n"
"fig, ax = plt.subplots(figsize=(14, 4 + 0.4 * len(all_algos)))\n"
"im = ax.imshow(pivot.values, cmap='RdYlGn', vmin=0, vmax=4, aspect='auto')\n"
"ax.set_xticks(range(pivot.shape[1]))\n"
"ax.set_xticklabels(pivot.columns, rotation=45, ha='right', fontsize=9)\n"
"ax.set_yticks(range(pivot.shape[0]))\n"
"ax.set_yticklabels(pivot.index, fontsize=10)\n"
"for i in range(pivot.shape[0]):\n"
"    for j in range(pivot.shape[1]):\n"
"        val = pivot.values[i, j]\n"
"        if np.isfinite(val):\n"
"            lbl = grade_labels.get(int(val), '?')\n"
"            ax.text(j, i, lbl, ha='center', va='center', fontsize=11,\n"
"                    fontweight='bold', color='white' if val <= 1 else 'black')\n"
"ax.set_title('ATE Grade Heatmap -- All Algorithms x (Regime / DOF)',\n"
"             fontsize=13, fontweight='bold')\n"
"plt.colorbar(im, ax=ax, ticks=[0,1,2,3,4], label='Grade',\n"
"             format=plt.FuncFormatter(lambda x, _: grade_labels.get(int(x), '')))\n"
"plt.tight_layout()\n"
"plt.savefig(os.path.join(PROJ, 'cross_method_grade_heatmap.png'),\n"
"            dpi=150, bbox_inches='tight')\n"
"plt.show()"
)

# ── Cell 23 ──
md("## S10 Final Summary")

# ── Cell 24: Summary ──
code(
"print('=' * 80)\n"
"print('  FINAL SUMMARY -- ALL ALGORITHMS')\n"
"print('=' * 80)\n"
"\n"
"algo_summary = df_cross.groupby('algorithm').agg(\n"
"    ATE_mean=('ATE', 'mean'), ATE_min=('ATE', 'min'),\n"
"    R2_mean=('R2_val', 'mean'), R2_max=('R2_val', 'max'),\n"
"    MSE_mean=('MSE_val', 'mean'), MSE_min=('MSE_val', 'min'),\n"
").sort_values('ATE_mean')\n"
"\n"
"print('\\n  Ranked by mean ATE (lower is better):')\n"
"print(algo_summary.to_string())\n"
"\n"
"best_ate = algo_summary.index[0]\n"
"best_r2  = algo_summary['R2_mean'].idxmax()\n"
"best_mse = algo_summary['MSE_mean'].idxmin()\n"
"print(f'\\n  Best by ATE:  {best_ate} ({algo_summary.loc[best_ate, \"ATE_mean\"]:.4f})')\n"
"print(f'  Best by R2:   {best_r2} ({algo_summary.loc[best_r2, \"R2_mean\"]:.4f})')\n"
"print(f'  Best by MSE:  {best_mse} ({algo_summary.loc[best_mse, \"MSE_mean\"]:.6f})')\n"
"\n"
"print(f'\\n--- Per-regime winners (best ATE) ---')\n"
"for regime in REGIMES:\n"
"    sub = df_cross[df_cross['regime'] == regime]\n"
"    w = sub.loc[sub['ATE'].idxmin()]\n"
"    print(f'  {regime.upper():10s} -> {w[\"algorithm\"]:14s} ATE={w[\"ATE\"]:.4f}({w[\"ate_grade\"]})')\n"
"\n"
"print(f'\\n--- Lambda effect (PySR algorithms) ---')\n"
"for algo in ['PySR', 'Hybrid PySR']:\n"
"    sub = df_pysr[df_pysr['algorithm'] == algo]\n"
"    nl = sub[sub['library'] == 'No-lam']['ATE'].mean()\n"
"    wl = sub[sub['library'] == 'With-lam']['ATE'].mean()\n"
"    delta = ((nl - wl) / nl * 100) if nl > 0 else 0\n"
"    better = 'With-lam' if wl < nl else 'No-lam'\n"
"    print(f'  {algo:14s}: No-lam={nl:.4f} With-lam={wl:.4f} -> {better} ({abs(delta):.1f}%)')\n"
"\n"
"print(f'\\n--- Hyperparameter effect ---')\n"
"for param in ['parsimony', 'maxsize']:\n"
"    print(f'\\n  {param}:')\n"
"    grp = df_pysr.groupby(param)['ATE'].agg(['mean', 'min'])\n"
"    for val, row in grp.iterrows():\n"
"        print(f'    {val}: mean_ATE={row[\"mean\"]:.4f} min_ATE={row[\"min\"]:.4f}')\n"
"\n"
"print(f'\\n--- ATE Grade Distribution ---')\n"
"gct = pd.crosstab(df_cross['algorithm'], df_cross['ate_grade'])\n"
"for g in ['A','B','C','D','F']:\n"
"    if g not in gct.columns: gct[g] = 0\n"
"print(gct[['A','B','C','D','F']].to_string())\n"
"\n"
"print(f'\\n{\"=\"*80}')\n"
"print(f'  PySR configs:     {len(df_pysr)}')\n"
"print(f'  Cross-comparison: {len(df_cross)}')\n"
"print(f'  Results:          pysr_sweep_results.csv')\n"
"print(f'{\"=\"*80}')"
)

# ── Write notebook ──
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.7"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_OUT, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Wrote {NB_OUT}")
print(f"  Cells: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='code')} code, "
      f"{sum(1 for c in cells if c['cell_type']=='markdown')} markdown)")
